### ISSUE TITLE
About the performance on Davis2017

### ISSUE THREAD

**Issue by speedinghzl** [linjieyangsc/video_seg#1]
@linjieyangsc Thank you very much for sharing. And I have the question about the performance on Davis2017.

After fine-tuning the network on DAVIS2017 (step 2), the performance becomes worse.  I am a bit confused. And It seems that you do not report the result in your paper. 

Thanks again!

**Comment by linjieyangsc** [comment]
@speedinghzl after fine-tuning the model on DAVIS17, the result is better on DAVIS16 val set but become worse on DAVIS17 val set. We are not sure of the actual cause yet, but should be related to the small size of DAVIS training set.

**Comment by speedinghzl** [comment]
Thanks!

**Comment by EternityZY** [comment]
Hello, how do you solve this problem?
