### ISSUE TITLE
Error while evaluating on DAVIS2017

### ISSUE THREAD

**Issue by mrayush18** [linjieyangsc/video_seg#12]
while running same command i am having some other error 

> Traceback (most recent call last):
  File "osmn_train_eval.py", line 198, in <module>
    osmn.test(dataset, args, checkpoint_path, args.result_path, config=config, batch_size=1)
  File "/home/ai/video_seg/osmn.py", line 318, in test
    guide_images, gb_images, images, save_names = dataset.next_batch(batch_size, 'test')
  File "/home/ai/video_seg/dataset_davis.py", line 209, in next_batch
    guide_label = Image.open(sample[1])
  File "/home/ai/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 20] Not a directory: './DAVIS/Annotations/480p_split/bike-packing/00031.png/00000.png'

I am running command 
`python osmn_train_eval.py --data_path ./DAVIS --whole_model_path  pretrained_model/ft_davis/ft_davis --result_path ./results --only_testing --data_version 2017 --gpu_id 0`

**Comment by linjieyangsc** [comment]
@mrayush18 please first download davis dataset and run the preprocess script following our guideline. Thanks.
