### ISSUE TITLE
low performance with provided model

### ISSUE THREAD

**Issue by huaxinxiao** [linjieyangsc/video_seg#2]
@linjieyangsc  With provided model and evaluation script, I get very low testing performance on davis-16 (stage1: 0.28, stage 2: 0.57).
Could you provide the results (davis-16 and davis-17) used in your paper?

**Comment by EternityZY** [comment]
Hello, how do you solve this problem?

**Comment by huaxinxiao** [comment]
@EternityZY  Yes. You need ensure the label in your mask is [0, 255] instead of [0, 1].

**Comment by InstantWindy** [comment]
@huaxinxiao  hello, how do you evaluate the performance ?Are labels in two categories? What should be the value of the label? I'm confused ,Thank you!
