### ISSUE TITLE
Obtained Stage 2 evaluation results on DAVIS2017

### ISSUE THREAD

**Issue by EternityZY** [linjieyangsc/video_seg#3]
Thank you for your work, I would like to ask questions about the score results.
The Stage 2 model obtains mIoU 49 on DAVIS 2017
The model is official model,but I couldn't get the results of the experiment. I did it exactly as indicated on github. If I didn't notice you, please help me correct it.
Thank you!

**Comment by linjieyangsc** [comment]
@EternityZY We obtain 52.5 with stage 1 model, the stage 2 model is actually worse. We did not know the case but may be related to overfitting issue. So I guess your number is about right.
