### ISSUE TITLE
What is the expected performance on Youtube-VOS?

### ISSUE THREAD

**Issue by DiligentPanda** [linjieyangsc/video_seg#6]
Can you provide the expected performance on Youtube-VOS dataset? That would be really helpful for me to diagnose my problem:  currently, I got quite low performance (below 45 on dev set). I think I must do sth wrong.

**Comment by linjieyangsc** [comment]
Our current performance is 0.512. You can check the tech report here: https://arxiv.org/pdf/1809.03327.pdf
Empirically, fine-tuning from the MS-COCO model provides better performance. Thanks.
