### ISSUE TITLE
Implement three measures

### ISSUE THREAD

**Issue by InstantWindy** [linjieyangsc/video_seg#8]
Hello! I am a newcomer to learning video segmentation. Do you implement three measures:region similarity,contour accuracy and temporal instability? Thank you !

**Comment by linjieyangsc** [comment]
Hi, for the measures, please refer to the code from DAVIS authors: https://github.com/davisvideochallenge/davis-2017

**Comment by InstantWindy** [comment]
Thank you!This code is for binary segmentation input,but Davis 2017 is a multi-class data set. How do you deal with it as binary?

**Comment by InstantWindy** [comment]
Your code is converted into a binary image in this way as shown below.But I wonder if it would be a problem to convert multiple categories into one category in davis 2017 dataset,in that way. Thank you!
![image](https://user-images.githubusercontent.com/23608180/49325136-49edc500-f578-11e8-9939-78b2312dcf08.png)

**Comment by linjieyangsc** [comment]
@InstantWindy please refer to script `ytvos_merge_result.py` to merge the binary result into a unified result. Generally it picks the label with highest probability among all the objects. This is not ideal but we did not find a better way yet.

**Comment by InstantWindy** [comment]
Thanks! When you use the class_balanced_cross_entropy_loss function to calculate loss, does the output of the network need to go through the Sigmoid function?

**Comment by linjieyangsc** [comment]
@InstantWindy  yes it does.
